name: Convert PDFs to Markdown

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

jobs:
  convert_pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install pdf2md-cli
        run: |
          npm install -g pdf2md-cli

      - name: Find and convert PDFs to Markdown
        run: |
          # 创建目标目录
          mkdir -p markdown

          # 遍历 Materials 目录下的所有子文件夹
          for dir in Materials/*/ ; do
            dirname=$(basename "$dir")
            if [[ "$dirname" =~ ^[0-9]{8}$ ]]; then
              echo "Processing directory: $dirname"

              # 遍历当前目录下的所有 PDF 文件
              for pdf in "$dir"*.pdf; do
                # 检查是否存在 PDF 文件
                if [[ -f "$pdf" ]]; then
                  filename=$(basename "$pdf" .pdf)
                  md_file="markdown/${dirname}_${filename}.md"

                  # 转换 PDF 为 Markdown
                  pdf2md "$pdf" > "$md_file"

                  echo "Converted $pdf to $md_file"
                fi
              done
            else
              echo "Skipping directory: $dirname (not matching date format)"
            fi
          done

      - name: Check for changes
        id: git_diff
        run: |
          git add markdown/
          # 检查是否有变化
          git diff --cached --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.changes == 'true'
        run: |
          git commit -m "Convert PDFs to Markdown on $(date +'%Y-%m-%d')"
          git push origin HEAD:${{ github.ref }}
